### ISSUE TITLE
Update to Antlr4

### ISSUE THREAD

**Issue by kaby76** [RupertAvery/csharpeval#18]
I have been implementing a similar project, when I just stumbled across this project. I was wondering why Antlr3 is used. Is there a reason to not move to Antlr4?

**Comment by RupertAvery** [comment]
Hi,

ANTLR3 was the first version I encountered and invested code in. It
unfortunately led to this mess of code.

There is a ANTLR4 branch I started working on, but it is still a work in
progress.

However with the opening up of Roslyn and its very similar ability to
compile an expression to a delegate function, including features such as a
"global" context for resolving symbols, along the difficulty of
implementing lambdas (specifically type inference), I haven't felt a need
to work on this project further.

Anyone is welcome to fork the project.

On Dec 23, 2016 11:46 PM, "Ken Domino" <notifications@github.com> wrote:

I have been implementing a similar project, when I just stumbled across
this project. I was wondering why Antlr3 is used. Is there a reason to not
move to Antlr4?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/RupertAvery/csharpeval/issues/18>, or mute the thread

**Comment by kaby76** [comment]
Thanks for the info!

Antlr4 is better, but not much. The Linq.Expression construction code used in the actions of the grammar are instead put in a tree walker "visitor", thus separated from the grammar. Either Antlr 3 or 4, it's all kind of messy. For the near term, I'm using a stripped-down C# grammar and doing something like what you've done here in this project.

I just looked at Roslyn, but it doesn't link with a PCL. It does link and run into a 1.x NET Standard library, but while I can parse and compile, I can't Assembly.Load(byte[]) the damn code. Roslyn does work in the platform-dependent Android or iOS DLLs, so I will try a bait/switch implementation.

--Ken
